name: Release

permissions:
  contents: write

on:
    workflow_dispatch:
    push:
        branches:
            - 'main'
        tags:
            - 'v*.*.*'

jobs:
  build_plugin:
    runs-on: ubuntu-latest
    container:
        image: archlinux:latest
    steps:
      - name: set git global safe directory
        run: |
          pacman -Syu git npm --noconfirm
          git config --global --add safe.directory $(realpath .)

      - uses: actions/checkout@v4

      - name: build plugin
        run: |
          npm i -g pnpm
          pnpm install --no-frozen-lockfile
          pnpm run build
          tar -czvf decky-terminal.tar.gz --transform 's,^,decky-terminal/,' dist py_modules *.py *.json *.md *.js LICENSE
      
      - name: show files
        run: |
          tar -tzvf decky-terminal.tar.gz
      
      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: decky-terminal
          path: decky-terminal.tar.gz

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build_plugin
    steps:
      - run: mkdir /tmp/artifacts

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          path: /tmp/artifacts

      - run: ls -R /tmp/artifacts

      - name: publish to github release
        uses: softprops/action-gh-release@v2
        with:
          files: /tmp/artifacts/decky-terminal/decky-terminal.tar.gz
          tag_name: ${{ github.ref_name }}
          draft: false
          generate_release_notes: true
          prerelease: contains(github.ref, 'pre')
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}